-- Clinical LIMS Schema: patients, samples, orders, variants
-- This is the source of truth for the schema -- keep it in version control.
-- No DROP statements here on purpose: this file only describes what the
-- tables should look like. For resetting a dev/test database, use the
-- separate reset_dev_db.sql, which is destructive and must never be run
-- against prod.
--
-- This schema is meant to be applied identically to both the test and
-- production database instances (see .env.test / .env.prod and
-- DatabaseManager in _scripts/core/database.py). Run this same file against
-- both so they never drift apart -- don't hand-edit one instance directly.

-- 1. Patients Table (Holds demographic data)
-- patient_id is generated by application code, e.g. 'YYYYMMDD-00001'
CREATE TABLE patients (
    patient_id VARCHAR(20) PRIMARY KEY,
    mrn VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    sex VARCHAR(10) NOT NULL,
    date_registered DATETIME NOT NULL DEFAULT GETDATE()
);

-- 2. Samples Table (Bridges Patient to their physical sample)
-- One MRN can have many samples (different draws over time).
-- sample_id is app-generated, e.g. 'SAM-YYYYMMDD-00001' -- this is the anchor ID.
CREATE TABLE samples (
    sample_id VARCHAR(40) PRIMARY KEY,
    patient_id VARCHAR(20) NOT NULL
        FOREIGN KEY REFERENCES patients(patient_id),
    date_collected DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX idx_samples_patient_id ON samples(patient_id);

-- 3. Orders / Tests Table (Links an assay to a sample)
-- One sample can have multiple test_codes ordered against it, and the same
-- test_code can be reordered on the same sample any number of times (e.g.
-- sequencing failed, repeat on the same extracted DNA/RNA). order_id is a
-- plain IDENTITY column, so SQL Server guarantees uniqueness with no app-side
-- locking or "next run number" computation needed.
CREATE TABLE orders (
    order_id INT IDENTITY(1,1) PRIMARY KEY,
    -- Friendly display ID, deterministic since it's derived from the stored
    -- IDENTITY value rather than GETDATE(), so it's safe to PERSIST.
    test_order_id AS ('ORD-' + CAST(order_id AS VARCHAR(10))) PERSISTED UNIQUE,
    sample_id VARCHAR(40) NOT NULL
        FOREIGN KEY REFERENCES samples(sample_id),
    test_code VARCHAR(50) NOT NULL,         -- e.g. 'Hereditary_Cancer', 'Whole_Exome'
    -- Optional traceability: when a user clicks "order another test" on a
    -- failed/completed order, this points back at the order it's repeating.
    -- NULL for a first attempt.
    repeat_of_order_id INT NULL
        FOREIGN KEY REFERENCES orders(order_id),
    date_ordered DATETIME NOT NULL DEFAULT GETDATE(),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Running', 'Completed', 'Failed', 'Cancelled'))
);
CREATE INDEX idx_orders_sample_id ON orders(sample_id);
CREATE INDEX idx_orders_repeat_of ON orders(repeat_of_order_id);

-- 4. Variants / Results Table (Holds final genomic outputs)
-- sample_id is denormalized here on purpose so results can be queried
-- without a join back through orders -- but it must always match the
-- sample_id on the parent order. Enforce that in your pipeline uploader code
-- (set variants.sample_id = orders.sample_id at insert time), since SQL
-- Server foreign keys alone can't cross-check a second table's column.
CREATE TABLE variants (
    variant_id INT IDENTITY(1,1) PRIMARY KEY,
    order_id INT NOT NULL
        FOREIGN KEY REFERENCES orders(order_id),
    sample_id VARCHAR(40) NOT NULL
        FOREIGN KEY REFERENCES samples(sample_id),
    chrom VARCHAR(5) NOT NULL,
    start_pos INT NOT NULL,
    end_pos INT NOT NULL,
    ref VARCHAR(MAX) NOT NULL,
    alt VARCHAR(MAX) NOT NULL,
    -- ref/alt can be arbitrarily long (structural variants), and SQL Server
    -- won't allow a MAX-length column as an index/constraint key. This hash
    -- stands in for (ref, alt) in the uniqueness check below.
    ref_alt_hash AS CONVERT(VARBINARY(32), HASHBYTES('SHA2_256', CONCAT(ref, '|', alt))) PERSISTED,
    classification VARCHAR(50) NOT NULL    -- Pathogenic, Likely Pathogenic, VUS, Likely Benign, Benign
        CHECK (classification IN ('Pathogenic', 'Likely Pathogenic', 'VUS', 'Likely Benign', 'Benign')),
    -- Prevents the pipeline uploader from inserting the same call twice on retry
    CONSTRAINT uq_variants_call UNIQUE (order_id, chrom, start_pos, ref_alt_hash)
);
CREATE INDEX idx_variants_sample_id ON variants(sample_id);
CREATE INDEX idx_variants_order_id ON variants(order_id);

